### ISSUE TITLE
CI: pull docker image results in "no space left on device" error.

### ISSUE THREAD

**Issue by yakutovicha** [aiidalab/ansible-role-aiidalab-server#29]
When running tests locally or on GitHub, I get the following error:

```
TASK [marvel_nccr.aiidalab_server : Pull the docker image aiidalab/aiidalab-docker-stack:latest.] ***
fatal: [instance]: FAILED! => {"changed": false, "msg": "Error pulling aiidalab/aiidalab-docker-stack - code: None message: failed to register layer: ApplyLayer exit status 1 stdout:  stderr: write /opt/conda/lib/python3.7/site-packages/plotly/validators/__pycache__/_isosurface.cpython-37.pyc: no space left on device"}
```

It looks to me that this is not related to the free space on the disc. I do have enough space on my laptop, but I am still getting the same error.

**Comment by ltalirz** [comment]
here is an example of a github action setup that works

https://github.com/dokku/ansible-dokku/blob/7e047c63395bfca4ede366a8c1b59ceeda023472/.github/workflows/ci.yml#L82-L87

https://github.com/dokku/ansible-dokku/blob/7e047c63395bfca4ede366a8c1b59ceeda023472/molecule/default/molecule.yml#L11-L12

**Comment by yakutovicha** [comment]
thanks, @ltalirz!
